[package]
name = "msp430emu"
version = "0.1.0"
authors = ["sapir <yasapir@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
arrayvec = "0.5.1"
pyo3 = { version = "0.9.0", features = ["extension-module"] }
