[package]
name = "pyucorremu"
version = "0.1.0"
authors = ["sapir <yasapir@gmail.com>"]
edition = "2018"

[dependencies]
microcorruption-emu = { path = "../microcorruption-emu" }
pyo3 = { version = "0.9.0", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]
