[package]
name = "microcorruption-emu"
version = "0.1.0"
authors = ["sapir <yasapir@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "0.5.1"
gdbstub = { git = "https://github.com/daniel5151/gdbstub/", features = ["std"] }
