[package]
name = "microcorruption-emu"
version = "0.1.0"
authors = ["sapir <yasapir@gmail.com>"]
edition = "2018"

[dependencies]
microcorruption-emu-core = { path = "../microcorruption-emu-core" }
rand = "0.7.3"
hex = "0.4.2"
